apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-pet-web-portal.fullname" . }}
  labels:
    {{- include "kube-pet-web-portal.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kube-pet-web-portal.selectorLabels" . | nindent 4 }}