openapi: 3.0.0
info:
  title: Pet API
  version: 1.0.0
  description: API for managing pet adoption and listings in Kube Pet application

paths:
  /pets:
    get:
      summary: List available pets
      responses:
        "200":
          description: List of available pets retrieved successfully

  /pets/{petId}:
    get:
      summary: Get pet details by ID
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pet details retrieved successfully
        "404":
          description: Pet not found

  /pets/{petId}/adopt:
    post:
      summary: Adopt a pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pet adoption request successful
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Pet not found
        "409":
          description: Pet already adopted

  /pets/admin/manage/{petId}:
    put:
      summary: Update pet information (Admin)
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PetUpdateRequest"
      responses:
        "200":
          description: Pet information updated successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden (Admin access required)
        "404":
          description: Pet not found

    delete:
      summary: Remove a pet listing (Admin)
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Pet listing removed successfully
        "401":
          description: Unauthorized
        "403":
          description: Forbidden (Admin access required)
        "404":
          description: Pet not found
