openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for managing user registration, login, and profiles in Kube Pet application

paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
      responses:
        "200":
          description: User registration successful
        "400":
          description: Bad request
        "409":
          description: User already exists

  /users/login:
    post:
      summary: Log in as an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
      responses:
        "200":
          description: User login successful
        "401":
          description: Unauthorized
        "404":
          description: User not found

  /users/profile:
    get:
      summary: Get user profile
      responses:
        "200":
          description: User profile retrieved successfully
        "401":
          description: Unauthorized
        "404":
          description: User not found

    put:
      summary: Update user profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProfileUpdateRequest"
      responses:
        "200":
          description: User profile updated successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: User not found

  /users/list:
    get:
      summary: List all registered users (Admin)
      responses:
        "200":
          description: List of users retrieved successfully
        "401":
          description: Unauthorized
        "403":
          description: Forbidden (Admin access required)
